### ISSUE TITLE
svg importer Error in Houdini 20

### ISSUE THREAD

**Issue by ReinhardKepplinger** [Aeoll/Aelib#16]
Hi, thank you so much for this svg importer - it works great in Houdini 19 but stopped working in 19.5 for me and this is the error i get in H20

for svg import export is the feature i miss most in Houdini as it saves a lot of time - so it would be awesome if someone could fix this

thanks in advance

Reinhard

Traceback (most recent call last):
  File "ae::Sop/SVG_Import::2, PythonModule", line 10, in <module>
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.506/houdini/python3.10libs\toolutils.py", line 1858, in createModuleFromSection
    return _createModule(module_name,
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.506/houdini/python3.10libs\toolutils.py", line 1840, in _createModule
    eval(code, module_dict)
  File "path", line 3, in <module>
ImportError: cannot import name 'MutableSequence' from 'collections' (C:\PROGRA~1\SIDEEF~1\HOUDIN~1.506\python310\lib\collections\__init__.py)

**Comment by Aeoll** [comment]
Thanks for the report - I'm not working in H20 yet so this will likely be fixed early next year when I am!

**Comment by ReinhardKepplinger** [comment]
thanks in advance for taking a look and for your awesome tools.
btw it also didn't work in 19.5 for me

**Comment by 444366454** [comment]
Many thanks to Aeollfor this long term update!
@Aeoll

**Comment by AlexeyAdamitsky** [comment]
It's a bummer this doesn't work in H20. Gettings this error.

```
Invalid source [/obj/logo/SVG_Import1/SVG_IMPORT_UPDATED](node:/obj/logo/SVG_Import1/SVG_IMPORT_UPDATED).
(Error: Python error: Traceback (most recent call last):
File "<stdin>", line 424, in <module>
File "<stdin>", line 388, in iterElements
File "<stdin>", line 388, in iterElements
File "<stdin>", line 395, in iterElements
File "<stdin>", line 373, in processLeaf
File "<stdin>", line 264, in createPath
File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.653/houdini/python3.10libs\hou.py", line 55050, in __getattr__
return _hou.HDAModule___getattr__(self, name)
AttributeError: 'module' object has no attribute 'path'
).
```

**Comment by sallaki** [comment]
Having this available in H20 would be incredible. 

I get the following error:
`Invalid source [/obj/font1/SVG_Import1/SVG_IMPORT_UPDATED](node:/obj/font1/SVG_Import1/SVG_IMPORT_UPDATED).
(Error: Python error: Traceback (most recent call last):
File "<stdin>", line 405, in <module>
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.688\python310\lib\xml\etree\ElementTree.py", line 1222, in parse
tree.parse(source, parser)
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.688\python310\lib\xml\etree\ElementTree.py", line 580, in parse
self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 1
).`

**Comment by Aeoll** [comment]
updates have been made for H20 + 20.5 support which should have fixed most issues with the SVG Importer

**Comment by Dragoy** [comment]
I'm getting that error, too:
```
Traceback (most recent call last):
  File "ae::Sop/SVG_Import::2, PythonModule", line 10, in <module>
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.332/houdini/python3.10libs\toolutils.py", line 1886, in createModuleFromSection
    return _createModule(module_name,
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.332/houdini/python3.10libs\toolutils.py", line 1868, in _createModule
    eval(code, module_dict)
  File "path", line 3, in <module>
ImportError: cannot import name 'MutableSequence' from 'collections' (C:\PROGRA~1\SIDEEF~1\HOUDIN~1.332\python310\lib\collections\__init__.py)
```


Use Houdini FX Version 20.5.332 - Py3.10

**Comment by Dragoy** [comment]
![image](https://github.com/user-attachments/assets/8f1c47ca-749a-4e0a-b54a-c41d745bd966)
Added a temporary solution
